spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/configuration_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}

server:
  port: 8082
