spring:
  datasource:
    url: jdbc:postgresql://student-db:5432/student_db
    username: postgres
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
